version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - blogdevdata:/usr/share/elasticsearch/data
    networks:
      - blogdevnetwork

volumes:
  blogdevdata:
    driver: local
networks:
  blogdevnetwork:
    driver: bridge